version: '3.3'
services:
    ignite-node-1:
        image: applem1support/ignite:2.12.0
        container_name: ignite-node-1
       # cpus: "0.4"
        environment:
            - CONFIG_URI=file:///home/user/4nodes/config/docker-ignite.xml
            - JVM_OPTS=-Xms512m -Xmx512m -server -XX:ActiveProcessorCount=1 -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true -Djava.net.preferIPv4Stack=true
        expose:
            - "47500-47509"
        networks:
            - ignite
        volumes:
            - "./ignite_config:/home/user/4nodes/config"
        ports:
            - "10800:10800"

    ignite-node-2:
        image: applem1support/ignite:2.12.0
        container_name: ignite-node-2
      #  cpus: "0.4"
        environment:
            - CONFIG_URI=file:///home/user/4nodes/config/docker-ignite.xml
            - JVM_OPTS=-Xms512m -Xmx512m -server -XX:ActiveProcessorCount=1 -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true -Djava.net.preferIPv4Stack=true
        expose:
            - "47500-47509"
        networks:
            - ignite
        volumes:
            - "./ignite_config:/home/user/4nodes/config"
        ports:
            - "10900:10800"
networks:
  ignite:
    driver: bridge